//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace panaderia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class familia
    {
        public familia()
        {
            this.producto = new HashSet<producto>();
        }
        [Required]
        public int Id { get; set; }
        [Required]
        public string nombre { get; set; }
        [Required]
        public int lineaId { get; set; }
        [Required]
        public virtual linea linea { get; set; }
        [Required]
        public virtual ICollection<producto> producto { get; set; }
    }
}
