//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace panaderia.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PanaderiaEntities : DbContext
    {
        public PanaderiaEntities()
            : base("name=PanaderiaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<linea> linea { get; set; }
        public DbSet<receta> receta { get; set; }
        public DbSet<producto> producto { get; set; }
        public DbSet<detalle_receta> detalle_receta { get; set; }
        public DbSet<familia> familia { get; set; }
        public DbSet<usuario> usuario { get; set; }
        public DbSet<rolusuario> rolusuario { get; set; }
        public DbSet<proveedor> proveedor { get; set; }
        public DbSet<compra> compra { get; set; }
        public DbSet<produccion> produccion { get; set; }
        public DbSet<medida> medida { get; set; }
    }
}
