//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace panaderia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class produccion
    {
        public int Id { get; set; }
        public System.DateTime fecha_produccion { get; set; }
        public int recetaId { get; set; }
        public int valor { get; set; }
        public int cantidad { get; set; }
    
        public virtual receta receta { get; set; }
    }
}
