//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace panaderia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class producto
    {
        public producto()
        {
            this.detalle_receta = new HashSet<detalle_receta>();
            this.compra = new HashSet<compra>();
        }
    
        public int Id { get; set; }
        public string nombre { get; set; }
        public int formato { get; set; }
        public int familiaId { get; set; }
        public int usuarioId { get; set; }
        public int medidaId { get; set; }
        public long precio { get; set; }
    
        public virtual ICollection<detalle_receta> detalle_receta { get; set; }
        public virtual familia familia { get; set; }
        public virtual usuario usuario { get; set; }
        public virtual ICollection<compra> compra { get; set; }
        public virtual medida medida { get; set; }
    }
}
