//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace panaderia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class proveedor
    {
        public proveedor()
        {
            this.compra = new HashSet<compra>();
        }
    
        public int rut { get; set; }
        public string nombre { get; set; }
    
        public virtual ICollection<compra> compra { get; set; }
    }
}
