//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace panaderia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View
    {
        public int Id { get; set; }
        public string nombre { get; set; }
        public int formato { get; set; }
        public int lineaId { get; set; }
        public int familiaId { get; set; }
        public int usuarioId { get; set; }
        public int stock { get; set; }
        public string precio_venta { get; set; }
        public int medidaId { get; set; }
    }
}
